src/LoggerWebInterface/Models/Log.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoggerWebInterface.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public long Id { get; set; }
        public System.DateTime Time { get; set; }
        public byte LevelId { get; set; }
        public Nullable<int> MethodId { get; set; }
        public string Message { get; set; }
        public string Exception { get; set; }
        public string Stacksources { get; set; }
        public string Context { get; set; }
    
        public virtual LogLevel LogLevel { get; set; }
        public virtual Method Method { get; set; }
    }
}

src/LoggerWebInterface/Controllers/LogsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LoggerWebInterface.Models;
using LogRepository.Entities;
using LogRepository.Repositories;
using MongoDB.Bson;

namespace LoggerWebInterface.Controllers
{
    public class LogsController : Controller
    {
        //private IRepository<Log> db = new MongoDbRepository<Log>();

        // GET: /Logs/
        public ActionResult Index(FilterClass filterClass)
        {
            filterClass.Filter();

            if (Request.IsAjaxRequest())
            {
                return PartialView("_LogsTable", filterClass);
            }
            return View(filterClass);
        }

        public ActionResult Details(string id)
        {
            /*if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }*/
            var filterClass = new FilterClass();
            var log = filterClass.GetLog(id);
            if (log == null)
            {
                return HttpNotFound();
            }
            return View(log);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/LoggerWebInterface/Views/Logs/Details.cshtml
@using LoggerWebInterface.Views.Helpers
@model LogRepository.Entities.Log

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div class="col-md-12">
    <h4>Log</h4>
	<hr />
    <dl class="dl-horizontal" >
        <dt>Сборка</dt>
        <dd>
            @Html.DisplayFor(model => model.Assembly)
        </dd>

        <dt>Класс</dt>
        <dd>
            @Html.DisplayFor(model => model.Class)
        </dd>

        <dt>Контекст</dt>
        <dd>
            @Html.DisplayFor(model => model.Context)
        </dd>

        <dt>Дата</dt>
        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>Путь к файлу</dt>
        <dd>
            @Html.DisplayFor(model => model.FilePath)
        </dd>

        <dt>Хост</dt>
        <dd>
            @Html.DisplayFor(model => model.Host)
        </dd>

        <dt>№ линии</dt>
        <dd>
            @Html.DisplayFor(model => model.LineNumber)
        </dd>

        <dt>Метод</dt>
        <dd>
            @Html.DisplayFor(model => model.Method)
        </dd>

        <dt>Сообщение</dt>
        <dd>
            <pre>
                @Html.DisplayFor(model => model.Message)
            </pre>
        </dd>

        <dt>Процесс</dt>
        <dd>
            @Html.DisplayFor(model => model.ProcessName)
        </dd>

        <dt>Исключение</dt>
        
            @Html.Raw(Html.ExceptionTree(Model.Exception))
            @*@Html.DisplayFor(model => model.Exception.Message)
            </dd>
            <dd>
                @Html.DisplayFor(model => model.Exception.Source)
            </dd>
            <dd>
                @Html.DisplayFor(model => model.Exception.StackTrace)*@
        
    </dl>
</div>
<p>
    @Html.ActionLink("Назад", "Index")
</p>

src/LoggerWebInterface/Views/Logs/Index.cshtml
@using LoggerWebInterface.Controllers
@using MongoDB.Bson
@model FilterClass

@Html.Partial("_SearchForm", new FilterClass())

<div>
    <table id="logTableAll" class="table" style='word-break: normal;'>
        <thead>
            <tr>
                <th style="width:150px">
                    @Html.Label("Время записи")
                </th>
                <th style="width:80px">
                    @Html.Label("Уровень")
                </th>
                <th>
                    @Html.Label("Хост")
                </th>
                <th>
                    @Html.Label("Процесс")
                </th>
                <th>
                    @Html.Label("Сообщение")
                </th>

                <th></th>
            </tr>
        </thead>

        <tbody id="logTable">
            @Html.Partial("_LogsTable", Model)
        </tbody>

        @* @Html.Hidden("maxObjectId", Model.MaxObjectId, new { @id = "maxObjectId" })*@

    </table>

</div>

src/LoggerWebInterface/Views/Logs/_LogsTable.cshtml
@using System.Globalization
@using LoggerWebInterface.Views.Helpers
@using LogRepository.Entities
@using Microsoft.Ajax.Utilities
@using MongoDB.Bson
@model LoggerWebInterface.Controllers.FilterClass
           
@if (Model != null)
{
    foreach (Log item in Model.Logs)
     {
         <tr class="@LogHelpers.ColorLevel(item.LogLevel)">
             @Html.HiddenFor(modelItem => item.Id.CreationTime, new {@id = "ObjIdCreateTime"})
             @Html.HiddenFor(modelItem => item.Id, new {@id = "ObjId"})
             <td class="utc-date nowrap">
                 @Html.DisplayFor(modelItem => item.Date)
             </td>
             <td>
                 <span class="@LogHelpers.ClassLevel(item.LogLevel)">@item.LogLevel</span>
                 @*@Html.DisplayFor(modelItem => item.LogLevel)*@
             </td>
             <td>
                 @Html.DisplayFor(modelItem => item.Host)
             </td>
             <td>
                 @Html.DisplayFor(modelItem => item.ProcessName)
             </td>
             <td>
                 <div class="formatting-content can-trim-content trimmed-content">@Html.DisplayFor(modelItem => item.Message)</div>
             </td>
             <td>
                 @Html.ActionLink("Детали", "Details", "Logs", new {id = item.Id.ToString()}, new {target = "_blank"})
             </td>
         </tr>
     }
}

src/LoggerWebInterface/Views/Logs/_SearchForm.cshtml
@model LoggerWebInterface.Controllers.FilterClass


<form class="form-horizontal" role="form" method="get" action="@Url.Action("Index", "Logs")"
      data-otf-ajax='true' data-otf-target="#logTable" id="filterForm">
    @Html.HiddenFor(model => model.MaxObjectId, new { @id = "maxObjectId" })
    @Html.AntiForgeryToken()

    <hr />
    @Html.ValidationSummary(true)
    <div class="col-md-9">
        <div class="form-group">
            <div class="col-md-3">
                <p class="text-muted">От</p>
                @Html.TextBoxFor(model => model.FromTime, new { @id = "fromTime", @class = "form-control  date-time-value", @placeholder = "01.01.2014 00:00:00" })
                @Html.ValidationMessageFor(model => model.FromTime)
            </div>
            <div class="col-md-3">
                <p class="text-muted">До</p>
                @Html.TextBoxFor(model => model.ToTime, new { @id = "toTime", @class = "form-control  date-time-value", @placeholder = "12.12.2014 23:59:59" })
                @Html.ValidationMessageFor(model => model.ToTime)
            </div>
            <div class="col-md-2">
                <p class="text-muted">Хосты</p>
                @Html.DropDownList("HostMultiselect.SelectedItems",
                new MultiSelectList(Model.HostMultiselect.AllItems, Model.HostMultiselect.SelectedItems),
                new { @id = "hostMultiselect", @class = "multiselect ", @multiple = "multiple" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-3">
                <p class="text-muted">Уровни логирования</p>
                @Html.DropDownList("LevelMultiselect.SelectedItems",
                new MultiSelectList(Model.LevelMultiselect.AllItems, Model.LevelMultiselect.SelectedItems),
                new { @id = "levelMultiselect", @class = "multiselect ", @multiple = "multiple" })
            </div>

            <div class="col-md-3">
                <p class="text-muted">Процессы</p>
                @Html.DropDownList("ProcessMultiselect.SelectedItems",
                new MultiSelectList(Model.ProcessMultiselect.AllItems, Model.ProcessMultiselect.SelectedItems),
                new { @id = "processMultiselect", @class = "multiselect ", @multiple = "multiple" })
            </div>
            
            <div class="col-md-3 form-inline">
                <p class="text-muted">Поиск по сообщению
                    <span class="tooltip-info glyphicon glyphicon-question-sign"
                          title="Введите регулярное выражение"></span></p>
                @Html.TextBoxFor(model => model.MessageRegex, new { @id="messageRegex", @class = "form-control"})
                
                <span id="regexError" style="color:red"></span>
            </div>
            
        </div>

    </div>
    
    <div class="col-md-3">
        <div class="panel panel-default" style="width:210px; border-color: white">
            <div class="panel-heading" style="height:80px; background: white">
                
                    <p>
                        <input type="checkbox" id="doUpdateOnInterval" checked="checked" placeholder="секунды" />
                        Автоматически
                    </p>
                
                
                <div class="form-inline">
                    <span style="float: left; position: relative; top: 6px; margin-right: 11px;">
                        каждые
                    </span>
                    <input type="number" class="form-control" style="margin: 1px; padding:3px; float: left; height: 25px; width: 80px" id="updateIntervalTime" value="5">

                    
                    <span style="float: left; position: relative; top: 7px; margin-left: 11px;">
                        сек
                    </span>
                    
                </div>
            </div>
            
            <div class="panel-body form-inline input-group">
                <button type="button" class="btn btn-default" style="width:177px" id="searchSubmitBtn">

                    <div class="pull-left" style="display:inline-block; margin-left:45px;">Обновить</div>
                    <div style="display: inline-block; float: right; position: relative; margin-right: 10px;">
                        <span class="spinner-wrapper" >
                            <span id="spinner-timer"></span>
                            <img class="hidden" id="spinner-load" src="~/Content/Images/circle-loading.gif" width="16" />
                        </span>
                    </div>
                </button>

            </div>
        </div>
    </div>
    <hr />
</form>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}